version: '2'
services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=esco
      - POSTGRES_PASSWORD=esco@escoiq.2024
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    ports:
        - "5105:5432"
  odoo17:
    image: odoo:17
    user: root
    depends_on:
      - db
    ports:
      - "17105:8069"
      - "27005:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=esco
      - PASSWORD=esco@escoiq.2024
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   
      # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
#      - ./enterprise17:/mnt/enterprise
      - ./etc:/etc/odoo
    restart: always             # run as a service
